In [2]:
import pandas as pd
df=pd.read_csv("data.csv")
df.head(7)

  Student_ID        Name Class  Maths  Science  English  Computer  Social
0    STU0001   Surya Raj     A     70       66       63        52      48
1    STU0002   Surya Das     A     89       39       38        46      62
2    STU0003  Ananya Das     A     60       88       63        92      70
3    STU0004  Aarav Devi     D     78       70       54        62      78
4    STU0005    Diya Raj     D     47       80       79        68      40
5    STU0006  Priya Iyer     A     83       45       72        81      59
6    STU0007   Priya Raj     A     64       72       45        64      47

In [3]:
df.tail()

    Student_ID         Name Class  Maths  Science  English  Computer  Social
995    STU0996   Ananya Raj     D     65       78       41        77      65
996    STU0997    Diya Nair     D     47       92       50        45      42
997    STU0998  Aarav Reddy     C     43       51       42        91      42
998    STU0999   Kavin Nair     D     43       48       42        41      72
999    STU1000  Rahul Reddy     A     87       64       36        93      84

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Student_ID  1000 non-null   object
 1   Name        1000 non-null   object
 2   Class       1000 non-null   object
 3   Maths       1000 non-null   int64
 4   Science     1000 non-null   int64
 5   English     1000 non-null   int64
 6   Computer    1000 non-null   int64
 7   Social      1000 non-null   int64
dtypes: int64(5), object(3)
memory usage: 62.6+ KB

In [9]:
df.columns

Index(['Student_ID', 'Name', 'Class', 'Maths', 'Science', 'English',
       'Computer', 'Social'],
      dtype='object')

In [7]:
df.describe()

             Maths      Science      English     Computer       Social
count  1000.000000  1000.000000  1000.000000  1000.000000  1000.000000
mean     67.317000    67.587000    67.606000    68.446000    68.198000
std      19.021681    19.479884    19.349604    18.555198    18.909955
min      35.000000    35.000000    35.000000    35.000000    35.000000
25%      51.000000    50.000000    50.000000    52.000000    52.000000
50%      67.000000    68.000000    68.000000    69.000000    68.000000
75%      84.000000    84.250000    85.000000    84.000000    84.000000
max     100.000000   100.000000   100.000000   100.000000   100.000000

In [11]:
df.isnull().sum()

Student_ID    0
Name          0
Class         0
Maths         0
Science       0
English       0
Computer      0
Social        0
dtype: int64

calculate total marks

In [32]:
Subjects=['Maths','Physics','Chemistry','English','Computer_Science']
df['total']=df[Subjects].sum(axis=1)
df[['Student_id','total',]].tail()

    Student_ID  total
995    STU0996    326
996    STU0997    276
997    STU0998    269
998    STU0999    246
999    STU1000    364