In [1]:
import pandas as pd
df=pd.read_csv("data.csv")
df.head(7)

  Student_ID        Name Class  Maths  Science  English  Computer  Social
0    STU0001   Surya Raj     A     70       66       63        52      48
1    STU0002   Surya Das     A     89       39       38        46      62
2    STU0003  Ananya Das     A     60       88       63        92      70
3    STU0004  Aarav Devi     D     78       70       54        62      78
4    STU0005    Diya Raj     D     47       80       79        68      40
5    STU0006  Priya Iyer     A     83       45       72        81      59
6    STU0007   Priya Raj     A     64       72       45        64      47

In [2]:
df.tail()

    Student_ID         Name Class  Maths  Science  English  Computer  Social
995    STU0996   Ananya Raj     D     65       78       41        77      65
996    STU0997    Diya Nair     D     47       92       50        45      42
997    STU0998  Aarav Reddy     C     43       51       42        91      42
998    STU0999   Kavin Nair     D     43       48       42        41      72
999    STU1000  Rahul Reddy     A     87       64       36        93      84